INSERT INTO TASK (TITLE, DESCRIPTION, COMPLETED) VALUES
('Offer Letter Signed', 'You have signed the FAANG company offer letter digitally.', TRUE),
('Background Verification', 'Background check successfully completed before Day 1.', TRUE),
('Pre-boarding Forms Submitted', 'You have submitted ID proofs, tax forms, and personal details.', TRUE),
('Attend Orientation Session', 'Join the company-wide new hire orientation via Zoom at 9 AM.', FALSE),
('Meet HR Representative', 'One-on-one with HR to review benefits, policies, and perks.', FALSE),
('Collect Laptop and Access Badge', 'Pick up your MacBook and building access badge from IT desk.', FALSE),
('Set Up Email and Calendar', 'Login to your company Gmail and sync your calendar.', FALSE),
('Install Development Tools', 'Install IDE (IntelliJ), Docker, Postman, and browser plugins.', FALSE),
('Connect to VPN', 'Set up and test VPN connection for secure access to internal tools.', FALSE),
('Join Slack Channels', 'Join team and org-level Slack channels for communication.', TRUE),
('Access GitHub Repositories', 'Get access to internal GitHub and clone onboarding repo.', FALSE),
('Run Starter Project', 'Build and run the engineering onboarding starter project.', FALSE),
('Review Engineering Wiki', 'Go through documentation on coding standards and deployment.', FALSE),
('Complete Security Training', 'Finish mandatory security and compliance training.', FALSE),
('Meet Your Manager', '1:1 with your manager to align on team goals and expectations.', TRUE),
('Meet Your Buddy', 'Introduce yourself to your onboarding buddy and schedule regular syncs.', FALSE),
('Join Team Stand-up', 'Attend your first team daily stand-up meeting.', FALSE),
('Create Dev Branch', 'Create a personal dev branch in your onboarding repo.', FALSE),
('Submit First Pull Request', 'Make a minor code change and submit your first PR.', FALSE),
('Complete Day 1 Survey', 'Submit feedback on your Day 1 onboarding experience.', FALSE);